### ISSUE TITLE
关于1.3.1版本使用的问题

### ISSUE THREAD

**Issue by 7ac9d42** [Thryanii/SecondClass#1]
1.3.0版本会间歇性出现login后刚完成课程加载就闪退的情况，1.3.1版本情况更甚以至于完全无法使用（每次出现），或者出现login卡住，下附上多次闪退后系统截出的报错：
![Screenshot_2023-09-24-11-22-23-330_com miui bugre](https://github.com/thriic/SecondClass/assets/110989625/4e2c68d2-7d7f-427c-9aa8-bedb1d9bf4b0)

**Comment by 7ac9d42** [comment]
补充：换回1.3.0可以正常使用

**Comment by thriic** [comment]
可否提供一下机型和安卓版本

**Comment by 7ac9d42** [comment]
> 可否提供一下机型和安卓版本

Redmi K60PRO 安卓13

**Comment by thriic** [comment]
我重新上传了release https://github.com/thriic/SecondClass/releases/tag/v1.3.1
试试这一版是否可行

**Comment by 7ac9d42** [comment]
> 我重新上传了release https://github.com/thriic/SecondClass/releases/tag/v1.3.1 试试这一版是否可行

可行，暂时未发现有什么问题，问题已消失，但是现在没法测试报名和签到功能

**Comment by momentfsff** [comment]
最近好像无法登录了

**Comment by thriic** [comment]
> 最近好像无法登录了

是超时未响应吗，这学期开始不知名原因webvpn登录很慢，特别是在晚上
